name: Build & Push Cloudshell Images

on:
  push:
    branches:
      - main
  schedule:
    # Run at 5am and 12pm PDT on weekdays
    # 5am PDT is 12pm UTC
    - cron: '0 12 * * 1-5'
    # 12pm PDT is 7pm UTC
    - cron: '0 19 * * 1-5'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Set up trivy.
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: '16384'
        temp-reserve-mb: '100'
        swap-size-mb: '8192'
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Create temporary trivy directories
      run: |
        sudo mkdir $GITHUB_WORKSPACE/trivy-tmp
        sudo mkdir $GITHUB_WORKSPACE/trivy-tmp/.cache
        echo "TMPDIR=$GITHUB_WORKSPACE/trivy-tmp" >> $GITHUB_ENV
        echo "TRIVY_CACHE_DIR=$GITHUB_WORKSPACE/trivy-tmp/.cache" >> $GITHUB_ENV

    # Download code.
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: Azure/CloudShell
        path: CloudShell

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Tag
      id: tag
      run: |
        cd CloudShell
        # Generate a tag based on the commit hash and current timestamp.
        # It is possible that the master may not change, so timestamp ensures that the tag is unique.
        echo "image_tag=$(git rev-parse --short HEAD)-$(date '+%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

    - name: Extract metadata labels for base image
      id: base-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/surajssd/cloudshell/base
        tags: |
          type=raw,value=latest
          type=raw,value=${{ steps.tag.outputs.image_tag }}

    - name: Base image
      uses: docker/build-push-action@v6
      with:
        context: CloudShell
        file: CloudShell/linux/base.Dockerfile
        push: true
        tags: ${{ steps.base-meta.outputs.tags }}
        labels: ${{ steps.base-meta.outputs.labels }}

    - name: Scan base image with Trivy
      id: trivy-base-scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'image'
        image-ref: ${{ env.REGISTRY }}/surajssd/cloudshell/base:${{ steps.tag.outputs.image_tag }}
        scanners: 'vuln,config'
        severity: 'HIGH,CRITICAL'

    - name: Extract metadata labels for tools image
      id: tools-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/surajssd/cloudshell/tools
        tags: |
          type=raw,value=latest
          type=raw,value=${{ steps.tag.outputs.image_tag }}

    - name: Tools image
      uses: docker/build-push-action@v6
      with:
        context: CloudShell
        file: CloudShell/linux/tools.Dockerfile
        push: true
        build-args: IMAGE_LOCATION=${{ env.REGISTRY }}/surajssd/cloudshell/base:${{ steps.tag.outputs.image_tag }}
        tags: ${{ steps.tools-meta.outputs.tags }}
        labels: ${{ steps.tools-meta.outputs.labels }}

    - name: Scan base image with Trivy
      id: trivy-tools-scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'image'
        image-ref: ${{ env.REGISTRY }}/surajssd/cloudshell/tools:${{ steps.tag.outputs.image_tag }}
        scanners: 'vuln,config'
        severity: 'HIGH,CRITICAL'
